theme = "black-and-light"
baseurl = "https://RockinWool.github.io/RFV/"
title = "Tar_nullaの部屋"
author = "RockinWool"
canonifyurls = true #対パスか
paginate = 10
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"

pygmentsstyle       = "perldoc"
pygmentscodefences  = true

[params]
  sitename = "Tar_nullaの部屋"
  disableWebFonts = false

[[menu.main]]
    name = "Twitter"
    url  = "https://twitter.com/vaex116"
[[menu.main]]
    name = "GitHub"
    url  = "https://github.com/RockinWool/talkings"
[[menu.main]]
    name = "black-and-light-theme(Hugo)"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"