theme = "black-and-light"
baseurl = "https://RockinWool.github.io/RFV/"
title = "Tar_nullaの部屋"
author = "RockinWool"
canonifyurls = true #対パスか
paginate = 10
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Tar_nullaの部屋"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Resume"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"